trigger: none

pr: none

parameters:
  - name: env
    type: string
    values:
      - Dev
      - QA
      - Prod

variables:
- template: ../config/common/common.yml

stages:

- stage: ValidateDS
  displayName: Validate Data Share Account and Data Share

  jobs:
  - job: Bicep_Validation
    displayName: Bicep Deployment Validation
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: 'Bicep Main Templates Validation'
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/landingzone/
        inlineScript: |
          $(var-bashPreInjectScript)
          echo "Validating templates for Landing Zone Data Share Deployment - ${{ parameters.env }}"
          az deployment sub validate --location $(deploymentRegion) --name 'validate-alz-ds-template' --template-file data-shares.bicep --parameters $(System.DefaultWorkingDirectory)/$(dsPathFromRoot)/${{ parameters.env }}/ds.parameters.json
          $(var-bashPostInjectScript)
    - task: AzureCLI@2
      displayName: 'Get Bicep Main Template Deployment What-If Result'
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/landingzone/
        inlineScript: |
          $(var-bashPreInjectScript)
          echo "Getting What-If result for Landing Zone Data Share Deployment - ${{ parameters.env }}"
          az deployment sub  what-if --location $(deploymentRegion) --name 'whatif-result-alz-ds-template' --template-file data-shares.bicep --parameters $(System.DefaultWorkingDirectory)/$(dsPathFromRoot)/${{ parameters.env }}/ds.parameters.json
          $(var-bashPostInjectScript)

- stage: DeployDS
  displayName: Deploy Data Share Account and Data Share

  jobs:
  - job: DeployDSInTheEnvironment
    displayName: Deploy Data Share in the Environment
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName:  Deploy Data Share
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: $(System.DefaultWorkingDirectory)/landingzone/
        inlineScript: |
          $(var-bashPreInjectScript)
          echo "Deploying Data Share Resources for Landing Zone - ${{ parameters.env }}"
          az deployment sub  create --location $(deploymentRegion) --name 'deploy-alz-ds' --template-file data-shares.bicep --parameters $(System.DefaultWorkingDirectory)/$(dsPathFromRoot)/${{ parameters.env }}/ds.parameters.json
          $(var-bashPostInjectScript)
