trigger: none

pr: none

parameters:
  - name: env
    type: string
    values:
      - Dev
      - QA
      - Prod
      - DataMgt

variables:
- template: ../config/common/common.yml
- group: 'Rogers-credentials'

stages:

- stage: ValidateVM
  displayName: Validate Virtual Machine

  jobs:
  - job: Bicep_Validation
    displayName: Bicep Deployment Validation
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: 'Bicep Main Templates Validation'
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/landingzone/
        inlineScript: |
          $(var-bashPreInjectScript)
          echo "Validating templates for Landing Zone Virtual Machine Deployment - ${{ parameters.env }}"
          az deployment sub validate --location $(deploymentRegion) --name 'validate-alz-vm-template' --template-file vm.bicep --parameters $(System.DefaultWorkingDirectory)/$(vmPathFromRoot)/${{ parameters.env }}/vm.parameters.json --parameters adminUsername=$(adminUsername) --parameters adminPassword=$(adminPassword)
          $(var-bashPostInjectScript)
    - task: AzureCLI@2
      displayName: 'Get Bicep Main Template Deployment What-If Result'
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/landingzone/
        inlineScript: |
          $(var-bashPreInjectScript)
          echo "Getting What-If result for Landing Zone Virtual Machine Deployment - ${{ parameters.env }}"
          az deployment sub  what-if --location $(deploymentRegion) --name 'whatif-result-alz-vm-template' --template-file vm.bicep --parameters $(System.DefaultWorkingDirectory)/$(vmPathFromRoot)/${{ parameters.env }}/vm.parameters.json --parameters adminUsername=$(adminUsername) --parameters adminPassword=$(adminPassword)
          $(var-bashPostInjectScript)

- stage: DeployVM
  displayName: Deploy Virtual Machine

  jobs:
  - job: DeployVMInTheEnvironment
    displayName: Deploy Virtual Machine in the Environment
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName:  Deploy Virtual Machine
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: $(System.DefaultWorkingDirectory)/landingzone/
        inlineScript: |
          $(var-bashPreInjectScript)
          echo "Deploying Virtual Machine Resources for Landing Zone - ${{ parameters.env }}"
          az deployment sub  create --location $(deploymentRegion) --name 'deploy-alz-vm' --template-file vm.bicep --parameters $(System.DefaultWorkingDirectory)/$(vmPathFromRoot)/${{ parameters.env }}/vm.parameters.json --parameters adminUsername=$(adminUsername) --parameters adminPassword=$(adminPassword)
          $(var-bashPostInjectScript)
