trigger: none

pr: none

parameters:
  - name: env
    type: string
    values:
      - dev
      - prod
      - hub

variables:
- template: ../config/common/common.yml

stages:

# VNET here
- stage: ValidateFirewallResources
  displayName: Validate Firewall Resources

  jobs:
  - job: Bicep_Validation
    displayName: Bicep Deployment Validation
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: 'Bicep Main Templates Validation'
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/landingzone/
        inlineScript: |
          $(var-bashPreInjectScript)
          echo "Validating templates for Landing Zone Azure Firewall - ${{ parameters.env }}"
          az deployment sub validate --location $(deploymentRegion) --name 'validate-alz-firewall-template' --template-file azure-firewall.bicep --parameters $(System.DefaultWorkingDirectory)/$(networkPathFromRoot)/hub/${{ parameters.env }}-azureFirewall.parameters.json
          $(var-bashPostInjectScript)
    - task: AzureCLI@2
      displayName: 'Get Bicep Main Template Deployment What-If Result'
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/landingzone/
        inlineScript: |
          $(var-bashPreInjectScript)
          echo "Getting What-If result for Landing Zone Azure Firewall Deployment - ${{ parameters.env }}"
          az deployment sub  what-if --location $(deploymentRegion) --name 'whatif-result-alz-firewall-template' --template-file azure-firewall.bicep --parameters $(System.DefaultWorkingDirectory)/$(networkPathFromRoot)/hub/${{ parameters.env }}-azureFirewall.parameters.json
          $(var-bashPostInjectScript)

- stage: DeployAzureFirewallResources
  displayName: Deploy Azure Firewall Resources

  jobs:
  - job: DeployAzureFirewallInTheEnvironment
    displayName: Deploy Azure Firewall in the Environment
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName:  Deploy Azure Firewall
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: $(System.DefaultWorkingDirectory)/landingzone/
        inlineScript: |
          $(var-bashPreInjectScript)
          echo "Deploying Firewall Resources for Landing Zone - ${{ parameters.env }}"
          az deployment sub  create --location $(deploymentRegion) --name 'deploy-alz-firewall' --template-file azure-firewall.bicep --parameters $(System.DefaultWorkingDirectory)/$(networkPathFromRoot)/hub/${{ parameters.env }}-azureFirewall.parameters.json
          $(var-bashPostInjectScript)