trigger: none

pr: none

parameters:
  - name: env
    type: string
    values:
      - Dev
      - QA
      - Prod

variables:
- template: ../config/common/common.yml
- group: 'Rogers-credentials'

stages:

- stage: ValidateSynapse
  displayName: Validate Synapse Workspace

  jobs:
  - job: Bicep_Validation
    displayName: Bicep Deployment Validation
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: 'Bicep Main Templates Validation'
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/landingzone/
        inlineScript: |
          $(var-bashPreInjectScript)
          echo "Validating templates for Landing Zone Synapse Workspace Deployment - ${{ parameters.env }}"
          az deployment sub validate --location $(deploymentRegion) --name 'validate-alz-sw-template' --template-file synapse-workspace.bicep --parameters $(System.DefaultWorkingDirectory)/$(synapsePathFromRoot)/${{ parameters.env }}/synapse.parameters.json --parameters sqlusername=$(sqlusername) --parameters sqlpassword=$(sqlpassword)
          $(var-bashPostInjectScript)
    - task: AzureCLI@2
      displayName: 'Get Bicep Main Template Deployment What-If Result'
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/landingzone/
        inlineScript: |
          $(var-bashPreInjectScript)
          echo "Getting What-If result for Landing Zone Synapse Workspace Deployment - ${{ parameters.env }}"
          az deployment sub  what-if --location $(deploymentRegion) --name 'whatif-result-alz-sw-template' --template-file synapse-workspace.bicep --parameters $(System.DefaultWorkingDirectory)/$(synapsePathFromRoot)/${{ parameters.env }}/synapse.parameters.json --parameters sqlusername=$(sqlusername) --parameters sqlpassword=$(sqlpassword)
          $(var-bashPostInjectScript)

- stage: DeploySynapse
  displayName: Deploy Synapse Workspace

  jobs:
  - job: DeploySWInTheEnvironment
    displayName: Deploy Synapse Workspace in the Environment
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName:  Deploy Synapse Workspace
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: $(System.DefaultWorkingDirectory)/landingzone/
        inlineScript: |
          $(var-bashPreInjectScript)
          echo "Deploying Synapse Workspace Resources for Landing Zone - ${{ parameters.env }}"
          az deployment sub  create --location $(deploymentRegion) --name 'deploy-alz-sw' --template-file synapse-workspace.bicep --parameters $(System.DefaultWorkingDirectory)/$(synapsePathFromRoot)/${{ parameters.env }}/synapse.parameters.json --parameters sqlusername=$(sqlusername) --parameters sqlpassword=$(sqlpassword)
          $(var-bashPostInjectScript)
