trigger: none

pr: none

parameters:
  - name: env
    type: string
    values:
      - dev
      - qa
      - prod
      - hub
      - datamgt

variables:
- template: ../config/common/common.yml

stages:

- stage: ValidateVNETPeeringResources
  displayName: Validate VNET Peering

  jobs:
  - job: Bicep_Validation
    displayName: Bicep Deployment Validation
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: 'Bicep Main Templates Validation'
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/landingzone/
        inlineScript: |
          $(var-bashPreInjectScript)
          echo "Validating templates for VNET Peering - ${{ parameters.env }}"
          az deployment sub validate --location $(deploymentRegion) --name 'validate-vnet-peering-template' --template-file peerings.bicep --parameters $(System.DefaultWorkingDirectory)/$(networkPathFromRoot)/${{ parameters.env }}/peering.parameters.json
          $(var-bashPostInjectScript)
    - task: AzureCLI@2
      displayName: 'Get Bicep Main Template Deployment What-If Result'
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/landingzone/
        inlineScript: |
          $(var-bashPreInjectScript)
          echo "Getting What-If result for VNET Peering - ${{ parameters.env }}"
          az deployment sub  what-if --location $(deploymentRegion) --name 'whatif-result-vnet-peering-template' --template-file peerings.bicep --parameters $(System.DefaultWorkingDirectory)/$(networkPathFromRoot)/${{ parameters.env }}/peering.parameters.json
          $(var-bashPostInjectScript)

- stage: DeployVNETPeeringResources
  displayName: Deploy VNET Peering

  jobs:
  - job: DeployVNETPeeringInTheEnvironment
    displayName: Deploy VNET Peering in the Environment
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName:  Deploy VNET Peering
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: $(System.DefaultWorkingDirectory)/landingzone/
        inlineScript: |
          $(var-bashPreInjectScript)
          echo "Deploying VNET Peering - ${{ parameters.env }}"
          az deployment sub  create --location $(deploymentRegion) --name 'deploy-vnet-peering' --template-file peerings.bicep --parameters $(System.DefaultWorkingDirectory)/$(networkPathFromRoot)/${{ parameters.env }}/peering.parameters.json
          $(var-bashPostInjectScript)